name: validate-terraform

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: terraform